$script = <<-SCRIPT
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt-get update && sudo apt-get install vault
SCRIPT

Vagrant.configure("2") do |config|
  
    config.vm.define "vault", autostart: true do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "vault"
      node.disksize.size = "20GB"
      node.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 2048
        v.name = "vault"
      end
    end
  end
  