Vagrant.configure("2") do |config|
  
    config.vm.define "ubuntu-18.04", autostart: true do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "ubuntu"
      node.disksize.size = "20GB"
      node.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 2048
        v.name = "ubuntu-18.04"
      end
    end
  end